// Update the data.js file to include better error handling for audio sources
const songs = [
    {
      id: 1,
      title: "Blinding Lights",
      artist: "The Weeknd",
      album: "After Hours",
      genre: "pop",
      cover: "https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526",
      src: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverwritten_Role_Playing_Game.mp3",
      added: "2023-01-15",
    },
    // {
    //   id: 2,
    //   title: "Levitating",
    //   artist: "Dua Lipa",
    //   album: "Future Nostalgia",
    //   genre: "pop",
    //   cover: "https://i.scdn.co/image/ab67616d0000b2734e0362c225863f6ae9c4a8be",
    //   src: "https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg",
    //   added: "2023-02-20",
    // },
    {
      id: 3,
      title: "Humble",
      artist: "Kendrick Lamar",
      album: "DAMN.",
      genre: "hip-hop",
      cover: "https://i.scdn.co/image/ab67616d0000b273d28d2ebdedb220e479743797",
      src: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3",
      added: "2023-03-05",
    },
    // {
    //   id: 4,
    //   title: "Bohemian Rhapsody",
    //   artist: "Queen",
    //   album: "A Night at the Opera",
    //   genre: "rock",
    //   cover: "https://i.scdn.co/image/ab67616d0000b273c5d5462e14a92d4f3fd2c9c7",
    //   src: "https://commondatastorage.googleapis.com/codeskulptor-assets/Evillaugh.ogg",
    //   added: "2023-01-10",
    // },
    // {
    //   id: 5,
    //   title: "Redbone",
    //   artist: "Childish Gambino",
    //   album: "Awaken, My Love!",
    //   genre: "r&b",
    //   cover: "https://i.scdn.co/image/ab67616d0000b273f78c8a4611eed93c8a0150b1",
    //   src: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverwritten_Role_Playing_Game.mp3",
    //   added: "2023-04-12",
    // },
    // {
    //   id: 6,
    //   title: "Bad Guy",
    //   artist: "Billie Eilish",
    //   album: "When We All Fall Asleep, Where Do We Go?",
    //   genre: "pop",
    //   cover: "https://i.scdn.co/image/ab67616d0000b273d55d10e0d95d40e12b82219d",
    //   src: "https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg",
    //   added: "2023-02-28",
    // },
    {
      id: 7,
      title: "Stairway to Heaven",
      artist: "Led Zeppelin",
      album: "Led Zeppelin IV",
      genre: "rock",
      cover: "https://i.scdn.co/image/ab67616d0000b273c8a11e48c91a982d086afc69",
      src: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3",
      added: "2023-01-05",
    },
    {
      id: 8,
      title: "Alright",
      artist: "Kendrick Lamar",
      album: "To Pimp a Butterfly",
      genre: "hip-hop",
      cover: "https://i.scdn.co/image/ab67616d0000b273cdb645498cd3d8a2db4d05e1",
      src: "https://commondatastorage.googleapis.com/codeskulptor-assets/Evillaugh.ogg",
      added: "2023-03-18",
    },
    {
      id: 9,
      title: "Dreams",
      artist: "Fleetwood Mac",
      album: "Rumours",
      genre: "rock",
      cover: "https://i.scdn.co/image/ab67616d0000b273e52a59a28efa4773dd2bfe1b",
      src: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverwritten_Role_Playing_Game.mp3",
      added: "2023-01-22",
    },
    {
      id: 10,
      title: "Hotline Bling",
      artist: "Drake",
      album: "Views",
      genre: "hip-hop",
      cover: "https://i.scdn.co/image/ab67616d0000b2739416ed64daf84936d89e671c",
      src: "https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg",
      added: "2023-02-15",
    },
  ]
  
  export default songs
  
  